web_server: yes

schedules: no
#   - tasks: '*'
#     interval:
#       hours: 1

templates:
  tv:
    regexp:
      reject:
        - x265: {from: title}
    series:
      settings:
        tv:
          exact: yes
          propers: 12 hours
          quality: 720p
      tv:
      - Westworld

    transmission:
      host: transmission
      port: 9091
      username: pi
      password: "123456"

tasks:
  eztvrss:
    rss: https://eztv.ag/ezrss.xml
    template: tv
    priority: 2
  sort_tv:
    priority: 2
    no_entries_ok: yes
    parsing:
      series: guessit
    filesystem:
      path: /downloads/complete
      regexp: '.*\.(avi|mkv|mp4)$'
      recursive: yes
    accept_all: yes
    thetvdb_lookup: yes
    require_field: series_name
    all_series:
      parse_only: yes
    exec:
      auto_escape: yes
      on_output:
        for_entries: |
          mkdir -p "/storage/tv/{{ series_name | replace(':', '') }}/Season {{ series_season }}" && cp "{{ location }}" "/storage/tv/{{ series_name | replace(':', '') }}/Season {{ series_season }}/{{ series_name  }} - {{ series_id }}{{ location | pathext }}"
  sort_movies:
    priority: 2
    no_entries_ok: yes
    filesystem:
      path: /downloads/complete
      regexp: '.*\.(avi|mkv|mp4)$'
      recursive: yes
    accept_all: yes
    require_field: movie_name
    imdb_lookup: yes
    exec:
      auto_escape: yes
      on_output:
        for_entries: |
          mkdir -p "/storage/movies/{{ movie_name | replace(':', '') }} ({{ movie_year }})" && cp "{{ location }}" "/storage/movies/{{ movie_name | replace(':', '') }} ({{ movie_year }})/{{ location | pathname }}{{ location | pathext }}"
  remove_stale_torrents:
    from_transmission:
      host: transmission
      port: 9091
      username: pi
      password: "123456"
    disable: [seen, seen_info_hash]
    if:
      - transmission_progress == 100: accept
      - not transmission_seed_ratio_ok and not transmission_idle_limit_ok: reject
    transmission:
      host: transmission
      port: 9091
      username: pi
      password: "123456"
      action: purge
